MyWidget

<MyWidget>
    orientation: "vertical"

    ActionBar:
        ActionView:
            ActionPrevious:
                title: "Data Annotator"
                with_previous: False

            FileManager:
                id: FileManager
                text: 'ファイル'
                ActionButton:
                    text: '読み込む'
                    on_press: app.root.ids['FileManager'].file_load()
                ActionButton:
                    text: '一時保存'
                    on_press: app.root.ids['FileManager'].file_save()
                ActionButton:
                    text: '書き出す'
                    on_press: app.root.ids['FileManager'].file_build_csv()

    MainArea:

<MainArea@BoxLayout>
    orientation: "horizontal"

    SelectArea:
        size_hint_x: 1

    AnnotateArea:
        size_hint_x: 4

<SelectArea>

    rows: 2
    canvas.after:
        Color:
            rgba: 1, 1, 1, 1
        Line:
            rectangle: self.x+1,self.y+1,self.width-1,self.height-1

    ScrollView:
        do_scroll_x: False
        size_hint_y: 9
        GridLayout:
            id: SelectDatas
            cols:1
            size_hint_y: None
            row_default_height: self.parent.height/10
            height: self.minimum_height
            #SelectButton:
                #text: "1:A"
            #SelectButton:
                #text: "2:B"
    GridLayout:
        cols: 2
        size_hint_y: 1
        orientation: "horizontal"
        Button:
            text: "<"
            on_press: root.data_left()
        Button:
            text: ">"
            on_press: root.data_right()

<SelectButton>
    text_size: self.size
    halign: 'left'
    valign: 'center'
    on_press: root.show(root.index)

<AnnotateArea>

    rows: 2

    BoxLayout:
        spacing: 10
        padding: 10

        BoxLayout:
            orientation: "vertical"
            spacing: 10
            padding: 10
            id: showArea
            canvas.before:
                Color:
                    rgba: .2, .2, .2, 1
                Rectangle:
                    pos: self.pos
                    size: self.size
            ShowText:
                text: "ファイル＞読み込む　から　.txtか.csvファイルを選択"
                halign: 'center'
                valign: 'center'

    ScrollView:
        spacing: 10
        padding: 10
        GridLayout:
            padding: 10
            id: pressArea
            cols:1
            size_hint_y: None
            row_default_height: self.parent.height/5
            height: self.minimum_height
            #AnswerButton:
                #text: "1:A"
            #AnswerButton:
                #text: "2:B"

<ShowText>
    text_size: self.size
    #color: 0,0,0,1
    halign: 'left'
    valign: 'top'

<AnswerButton>
    text_size: self.size
    halign: 'left'
    valign: 'center'
    on_press: root.put_answer(root.index, root.answer)

<CreateAnswerButton>
    text_size: self.size
    halign: 'left'
    valign: 'center'
    on_press: root.add_answers(root.index);

<CreateAnswerDialog>
    text_input: text_input
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        cols:2

        TextInput:
            focus: True
            hint_text: "ここに選択肢名を入力"
            id: text_input
            size_hint_y: None
            height: 30
            multiline: False

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "キャンセル"
                on_release: root.cancel()

            Button:
                text: "作成"
                on_release: root.make(root.index, text_input.text)
